insert into Species (SpeciesName) values ('Dog');
insert into Species (SpeciesName) values ('Cat');
insert into Species (SpeciesName) values ('Horse');
insert into Species (SpeciesName) values ('Snake');
insert into Species (SpeciesName) values ('Lizard');
insert into Species (SpeciesName) values ('Turtle');
insert into Species (SpeciesName) values ('Frog');
insert into Species (SpeciesName) values ('Bird');
insert into Species (SpeciesName) values ('Fish');
insert into Species (SpeciesName) values ( 'Cow');
insert into Species (SpeciesName) values ( 'Sheep');
insert into Species (SpeciesName) values ( 'Goat');
insert into Species (SpeciesName) values ( 'Ferret');
insert into Species (SpeciesName) values ( 'Hamster');
insert into Species (SpeciesName) values ( 'Salamander');
insert into Species (SpeciesName) values ( 'Rabbit');
insert into Species (SpeciesName) values ( 'Guinea Pig');
insert into Species (SpeciesName) values ( 'Pig');
insert into Species (SpeciesName) values ( 'Mouse');
insert into Species (SpeciesName) values ( 'Rat');
